### ISSUE TITLE
Lexical or Preprocessor Issue with Xcode 9.0.1 and Cocoapods

### ISSUE THREAD

**Issue by CassiusPacheco** [launchdarkly/ios-client#118]
After updating to Xcode 9.0.1 I've been getting an issue on LaunchDarkly SDK. I tried version 2.7.0 and 2.8.0 and both have this issue, it doesn't compile due to a missing file.

Have a look at the print screen below. Let me know if you need anything else.

![launchdarkly](https://user-images.githubusercontent.com/662062/31641974-07ac463a-b334-11e7-91b9-55a9d29cf4cc.png)

**Comment by CassiusPacheco** [comment]
@arun251 @danialzahid94 could you guys please have a look at this issue and give me further instructions. Thanks!

**Comment by arun251** [comment]
Hi @CassiusPacheco,
Thanks for that very helpful screenshot. In iOS SDK 2.5.1, we updated dependency `DarklyEventSource` to 3.0.0, which included prefixing public symbols (and filenames) with `LD` because a customer experienced some symbol name conflicts. I can't explain why you're seeing what you're seeing, but it seems that the version of `LDClientManager.m` is from an earlier version. Perhaps you could clear the `LaunchDarkly` Pods folder and try to update again?

**Comment by CassiusPacheco** [comment]
Hi @arun251, thanks for the quick answer! Weirdly CocoaPods was updating LaunchDarkly but not the dependencies, deleting everything and re-running it worked. I should have expected that from CocoaPods 🙄

Thanks again for the quick answer!
