### ISSUE TITLE
Flag is not returned correctly after updating user

### ISSUE THREAD

**Issue by argon** [launchdarkly/ios-client#22]
Issue #19 is still not resolved, occurring with code from `master`

**Comment by cmavromoustakos** [comment]
@argon 

I had asked you to elaborate on the issue in ticket #19 and had not received a response.

 If the issue is that the first time you request a flag when switching users then the default flags will be returned. On subsequent calls to toggle (as long as the response has returned from the server) you should see the correct values.

If you need to wait for the correct values you can use:

    LDClient *client = [LDClient sharedInstance];
    LDConfigBuilder *config = [[LDConfigBuilder alloc] init];
    [config withApiKey:@"your-api-key"];

    client.delegate = self;

and then implement the userDidUpdate delegate method which will be called every time the server returns with an updated config:

    +(void) userDidUpdate {
        LDClient *client = [LDClient sharedInstance];
        LDUser *user = client.user;
    }

The issue you described in #19 is that after switching to an anonymous user the values are no longer returned which we have not been able to reproduce.

Gus

**Comment by argon** [comment]
I apologise for the delay in my previous response. The issue was that switching _from_ anonymous to a known user (which had the correct values in the response) was still returning the incorrect value when toggle was called even *after* the response was returned and saved.

Having tried again, clearing all caches and reinstalling the app it seems to be working now so there must have been something stale.

**Comment by cmavromoustakos** [comment]
Thanks @argon
