### ISSUE TITLE
Add inspectors to this SDK

### ISSUE THREAD

**Issue by shanepadgett** [launchdarkly/ios-client#368]
**Is your feature request related to a problem? Please describe.**
We would like to use the inspectors feature that is available via the Javascript SDKs in our iOS project.

**Describe the solution you'd like**
Add inspector capability to this SDK.

**Describe alternatives you've considered**
None

**Additional context**
We use Datadog's RUM product and they support flag data gathering, but not from LD since inspectors aren't supported in the SDK.

**Comment by tanderson-ld** [comment]
Hi @shanepadgett , thank you for reaching out and letting us know you are interested in this feature.  I will take a note to discuss with the team.

**Comment by tanderson-ld** [comment]
@shanepadgett, could you provide us more insight into what types of information you are looking to collect?

We are currently working on adding Hooks support to several of our server side SDKs.  Currently the Hooks contain `beforeEvaluation` and `afterEvaluation` callbacks as part of the "Evaluation Series".  We may bring support for this Hooks callback interface to the client SDKs in the future so that logging and analytics integrations can be made more easily.  Does that sound like what you are looking for?

[Go docs for Hook interface](https://pkg.go.dev/github.com/launchdarkly/go-server-sdk/v7@v7.4.0/ldhooks#Hook)

[Docs on OpenTelemetry integration that uses the Hook interface](https://docs.launchdarkly.com/sdk/features/open-telemetry)

**Comment by shanepadgett** [comment]
The Datadog documentation for adding automatic feature flag tracking only shows support for browser SDK and mentions putting in a request for this feature with your team. Here you will see how the inspector would work for web, but if you click on iOS for launch darkly it mentions no support. It sounds like your hooks are like inspectors for the web sdk?

https://docs.datadoghq.com/real_user_monitoring/guide/setup-feature-flag-data-collection/?tab=browser#launchdarkly-integration

https://docs.launchdarkly.com/sdk/features/inspectors

**Comment by tanderson-ld** [comment]
@shanepadgett, good news!  A team member is starting on the implementation of Hooks for this SDK.  Hooks is superseding the inspector capability and will meet your needs here.  We intend to reach out to Datadog to have them update their docs.  We'll respond back here again once the implementation is complete.

**Comment by keelerm84** [comment]
@shanepadgett the hook implementation has been released in v9.7.0. 

Here are some key points of documentation to help you get started.

* You will need to implement the [Hook protocol](https://launchdarkly.github.io/ios-client-sdk/Protocols/Hook.html) in order to take advantage of the new hook functionality.
* Hooks can be registered through the [LDConfig](https://launchdarkly.github.io/ios-client-sdk/Structs/LDConfig.html#/s:12LaunchDarkly8LDConfigV5hooksSayAA4Hook_pGvp).

Please let us know if you have any questions!
